### ISSUE TITLE
Generating a ZIP code using the stateAbbreviation parameter doesn't work correctly

### ISSUE THREAD

**Issue by CJMarinacci** [RimuTec/Faker#1]
The resulting ZIP code is always 5 characters, and the last two characters are '#'.

**Comment by ManfredLange** [comment]
@CJMarinacci Thank you for reporting this issue. I can reproduce this problem.

**Comment by ManfredLange** [comment]
Version 1.2.0 should fix this. Please confirm and re-open this issue if that is not the case. Please provide a code example that reproduced the problem if this issue is not fixed yet.

@CJMarinacci Thank you again for taking the time to report this issue. Very much appreciated! Your effort is a contribution that other users will benefit from as well.
